package local:knitwit;

world knitwit{
    export knitwit: func(wit-paths: list<string>, worlds: list<string>, output-world: option<string>, output-package: option<string>) -> result<string, string>;
}